// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("API.Models.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProducto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockActual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdInventario");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdProducto", "IdSucursal")
                        .IsUnique();

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("API.Models.Modulo", b =>
                {
                    b.Property<int>("IdModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdModulo");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("API.Models.ModuloCategoria", b =>
                {
                    b.Property<int>("IdModuloCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdModulo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdModuloCategoria");

                    b.HasIndex("IdModulo");

                    b.ToTable("ModuloCategorias");
                });

            modelBuilder.Entity("API.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdProducto")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdSucursalDestino")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdSucursalOrigen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdSucursalDestino");

                    b.HasIndex("IdSucursalOrigen");

                    b.HasIndex("IdUsuario");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("API.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroParte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProducto");

                    b.HasIndex("NumeroParte")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("API.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("API.Models.RolModuloPermiso", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdModuloCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PuedeEliminar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PuedeEscribir")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PuedeLeer")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdRol", "IdModuloCategoria");

                    b.HasIndex("IdModuloCategoria");

                    b.ToTable("RolModuloPermisos");
                });

            modelBuilder.Entity("API.Models.Sucursal", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("IdSucursal");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ContraseniaHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ContraseniaSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("API.Models.UsuarioSucursal", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUsuario", "IdSucursal");

                    b.HasIndex("IdSucursal");

                    b.ToTable("UsuarioSucursales");
                });

            modelBuilder.Entity("API.Models.Inventario", b =>
                {
                    b.HasOne("API.Models.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.Sucursal", "Sucursal")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("API.Models.ModuloCategoria", b =>
                {
                    b.HasOne("API.Models.Modulo", "Modulo")
                        .WithMany("ModuloCategorias")
                        .HasForeignKey("IdModulo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("API.Models.MovimientoInventario", b =>
                {
                    b.HasOne("API.Models.Producto", "Producto")
                        .WithMany("MovimientosInventario")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.Sucursal", "SucursalDestino")
                        .WithMany("MovimientosDestino")
                        .HasForeignKey("IdSucursalDestino")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.Models.Sucursal", "SucursalOrigen")
                        .WithMany("MovimientosOrigen")
                        .HasForeignKey("IdSucursalOrigen")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.Models.Usuario", "Usuario")
                        .WithMany("MovimientosInventario")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("SucursalDestino");

                    b.Navigation("SucursalOrigen");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API.Models.RolModuloPermiso", b =>
                {
                    b.HasOne("API.Models.ModuloCategoria", "ModuloCategoria")
                        .WithMany("RolModuloPermisos")
                        .HasForeignKey("IdModuloCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.Rol", "Rol")
                        .WithMany("RolModuloPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModuloCategoria");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("API.Models.Usuario", b =>
                {
                    b.HasOne("API.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("API.Models.UsuarioSucursal", b =>
                {
                    b.HasOne("API.Models.Sucursal", "Sucursal")
                        .WithMany("UsuarioSucursales")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Models.Usuario", "Usuario")
                        .WithMany("UsuarioSucursales")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API.Models.Modulo", b =>
                {
                    b.Navigation("ModuloCategorias");
                });

            modelBuilder.Entity("API.Models.ModuloCategoria", b =>
                {
                    b.Navigation("RolModuloPermisos");
                });

            modelBuilder.Entity("API.Models.Producto", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("MovimientosInventario");
                });

            modelBuilder.Entity("API.Models.Rol", b =>
                {
                    b.Navigation("RolModuloPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("API.Models.Sucursal", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("MovimientosDestino");

                    b.Navigation("MovimientosOrigen");

                    b.Navigation("UsuarioSucursales");
                });

            modelBuilder.Entity("API.Models.Usuario", b =>
                {
                    b.Navigation("MovimientosInventario");

                    b.Navigation("UsuarioSucursales");
                });
#pragma warning restore 612, 618
        }
    }
}
